<?xml version="1.0" encoding="UTF-8"?>
<!--
  =====================================================================
  Dfdl schema definition for: Iex IexEquities DeepPlus v1.0.1

  Protocol:
    Organization: Investors Exchange
    Protocol: DeepPlus
    Encoding: Investors Exchange Transport Protocol
    Version: 1.0.1
    Date: 9/30/2024
    Specification: IEX_DEEP+ Specification.pdf

  Script:
    Generator: 1.0.0.0
    License: Public/GPLv3
    Authors: Omi Developers

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under
  the license noted above.

  The Binary Data Compiler technologies used to produce this file
  are the subject of patents owned by Scaled Sources LLC.  Those patent
  rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en

  For full Omi information:
    https://github.com/Open-Markets-Initiative/Directory
  =====================================================================
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:tns="urn:omi:iexequities:deepplus:v1:0:1" targetNamespace="urn:omi:iexequities:deepplus:v1:0:1">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="littleEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="packet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="iextpHeader" type="tns:iextpHeader_t" />
        <xs:element name="messages" type="tns:message_t" maxOccurs="unbounded">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element occursCountKind="expression" occursCount="{ ../iextpHeader/messageCount }" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="iextpHeader_t">
    <xs:sequence>
      <xs:element name="version" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="messageProtocolId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="channelId" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="sessionId" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="payloadLength" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="messageCount" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="streamOffset" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="firstMessageSequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="sendTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="message_t">
    <xs:sequence>
      <xs:element name="messageHeader" type="tns:messageHeader_t" />
      <xs:element name="messageData">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../messageHeader/messageLength + 2 - 3 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../messageHeader/messageType) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="systemEventMessage" type="tns:systemEventMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="S" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="securityDirectoryMessage" type="tns:securityDirectoryMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="D" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradingStatusMessage" type="tns:tradingStatusMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="H" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="retailLiquidityIndicatorMessage" type="tns:retailLiquidityIndicatorMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="I" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="operationalHaltStatusMessage" type="tns:operationalHaltStatusMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="O" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="shortSalePriceTestStatusMessage" type="tns:shortSalePriceTestStatusMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="P" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="securityEventMessage" type="tns:securityEventMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="E" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="addOrderMessage" type="tns:addOrderMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="a" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderModifyMessage" type="tns:orderModifyMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="M" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderDeleteMessage" type="tns:orderDeleteMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="R" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderExecutedMessage" type="tns:orderExecutedMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="L" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradeMessage" type="tns:tradeMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="T" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradeBreakMessage" type="tns:tradeBreakMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="B" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="clearBookMessage" type="tns:clearBookMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="C" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="messageHeader_t">
    <xs:sequence>
      <xs:element name="messageLength" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="messageType" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="systemEventMessage_t">
    <xs:sequence>
      <xs:element name="systemEvent" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="securityDirectoryMessage_t">
    <xs:sequence>
      <xs:element name="securityDirectoryFlags" type="tns:securityDirectoryFlags_t" />
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="roundLotSize" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="adjustedPocPrice" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="luldTier" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="securityDirectoryFlags_t">
    <xs:sequence>
      <xs:element name="unused5" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="5" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="etp" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="whenIssued" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="testSecurity" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradingStatusMessage_t">
    <xs:sequence>
      <xs:element name="tradingStatus" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reason" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="retailLiquidityIndicatorMessage_t">
    <xs:sequence>
      <xs:element name="retailLiquidityIndicator" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="operationalHaltStatusMessage_t">
    <xs:sequence>
      <xs:element name="operationalHaltStatus" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="shortSalePriceTestStatusMessage_t">
    <xs:sequence>
      <xs:element name="shortSalePriceTestStatus" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="detail" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="securityEventMessage_t">
    <xs:sequence>
      <xs:element name="securityEvent" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="addOrderMessage_t">
    <xs:sequence>
      <xs:element name="side" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderId" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="size" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderModifyMessage_t">
    <xs:sequence>
      <xs:element name="modifyFlags" type="tns:modifyFlags_t" />
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderIdReference" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="size" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="modifyFlags_t">
    <xs:sequence>
      <xs:element name="unused7" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="priority" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderDeleteMessage_t">
    <xs:sequence>
      <xs:element name="reserved1" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderIdReference" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderExecutedMessage_t">
    <xs:sequence>
      <xs:element name="saleConditionFlags" type="tns:saleConditionFlags_t" />
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderIdReference" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="size" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeId" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="saleConditionFlags_t">
    <xs:sequence>
      <xs:element name="unused3" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="3" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="singlepriceCrossTrade" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeThroughExempt" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="oddLot" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="extendedHours" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="intermarketSweep" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradeMessage_t">
    <xs:sequence>
      <xs:element name="saleConditionFlags" type="tns:saleConditionFlags_t" />
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="size" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeId" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradeBreakMessage_t">
    <xs:sequence>
      <xs:element name="saleConditionFlags" type="tns:saleConditionFlags_t" />
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="size" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeId" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="clearBookMessage_t">
    <xs:sequence>
      <xs:element name="reserved1" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>