<?xml version="1.0" encoding="UTF-8"?>
<!--
  Dfdl schema definition for: Bse BseIndia Eobi v1.4

  Protocol:
    Organization: BSE Limited
    Protocol: Enhanced Order Book Interface
    Encoding: Flat Binary Encoding
    Version: 1.4
    Date: 7/14/2025
    Specification: EOBI_Data_Manual_V1.4.pdf

  Script:
    Generator: 1.0.0.0
    License: Public/GPLv3
    Authors: Omi Developers

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under
  the license noted above.

  The protocol compiler technologies used to produce this file
  are the subject of patents owned by Scaled Sources LLC.  Those patent
  rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en

  Open Markets Initiative website:
    https://openmarketsinitiative.com
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:tns="urn:omi:bseindia:eobi:v1:4" targetNamespace="urn:omi:bseindia:eobi:v1:4">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="littleEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="packet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="packetHeader" type="tns:packetHeader_t" />
        <xs:element name="message" type="tns:message_t" maxOccurs="unbounded">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element occursCountKind="implicit" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="packetHeader_t">
    <xs:sequence>
      <xs:element name="eobiHeader" type="tns:eobiHeader_t" />
      <xs:element name="applSeqNum" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketSegmentId" type="xs:int">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="partitionId" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="completionIndicator" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="applSeqResetIndicator" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad5" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="5" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="eobiHeader_t">
    <xs:sequence>
      <xs:element name="bodyLen" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="templateId">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedShort">
            <xs:enumeration value="13001">
              <xs:annotation>
                <xs:documentation>Heartbeat Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13600">
              <xs:annotation>
                <xs:documentation>Product Summary Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13602">
              <xs:annotation>
                <xs:documentation>Snapshot Order Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13601">
              <xs:annotation>
                <xs:documentation>Instrument Summary Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13500">
              <xs:annotation>
                <xs:documentation>Auction Best Bid Offer Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13501">
              <xs:annotation>
                <xs:documentation>Auction Clearing Price Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13504">
              <xs:annotation>
                <xs:documentation>Top Of Book Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13100">
              <xs:annotation>
                <xs:documentation>Order Add Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13101">
              <xs:annotation>
                <xs:documentation>Order Modify Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13106">
              <xs:annotation>
                <xs:documentation>Order Modify Same Priority Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13102">
              <xs:annotation>
                <xs:documentation>Order Delete Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13103">
              <xs:annotation>
                <xs:documentation>Order Mass Delete Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13105">
              <xs:annotation>
                <xs:documentation>Partial Order Execution Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13104">
              <xs:annotation>
                <xs:documentation>Full Order Execution Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13200">
              <xs:annotation>
                <xs:documentation>Trade Reversal Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13202">
              <xs:annotation>
                <xs:documentation>Execution Summary Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13203">
              <xs:annotation>
                <xs:documentation>Instrument Info Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13204">
              <xs:annotation>
                <xs:documentation>Lpp Range Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13300">
              <xs:annotation>
                <xs:documentation>Product State Change Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13301">
              <xs:annotation>
                <xs:documentation>Instrument State Change Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13400">
              <xs:annotation>
                <xs:documentation>Add Complex Instrument Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13002">
              <xs:annotation>
                <xs:documentation>Packet Header</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="msgSeqNum" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="message_t">
    <xs:sequence>
      <xs:element name="messageHeader" type="tns:messageHeader_t" />
      <xs:element name="payload">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../messageHeader/bodyLen - 8 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../messageHeader/templateId) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="heartbeatMessage" type="tns:heartbeatMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13001" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="productSummaryMessage" type="tns:productSummaryMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13600" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="snapshotOrderMessage" type="tns:snapshotOrderMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13602" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="instrumentSummaryMessage" type="tns:instrumentSummaryMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13601" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="auctionBestBidOfferMessage" type="tns:auctionBestBidOfferMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13500" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="auctionClearingPriceMessage" type="tns:auctionClearingPriceMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13501" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="topOfBookMessage" type="tns:topOfBookMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13504" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderAddMessage" type="tns:orderAddMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13100" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderModifyMessage" type="tns:orderModifyMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13101" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderModifySamePriorityMessage" type="tns:orderModifySamePriorityMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13106" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderDeleteMessage" type="tns:orderDeleteMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13102" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderMassDeleteMessage" type="tns:orderMassDeleteMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13103" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="partialOrderExecutionMessage" type="tns:partialOrderExecutionMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13105" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="fullOrderExecutionMessage" type="tns:fullOrderExecutionMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13104" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradeReversalMessage" type="tns:tradeReversalMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13200" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="executionSummaryMessage" type="tns:executionSummaryMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13202" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="instrumentInfoMessage" type="tns:instrumentInfoMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13203" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="lppRangeMessage" type="tns:lppRangeMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13204" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="productStateChangeMessage" type="tns:productStateChangeMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13300" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="instrumentStateChangeMessage" type="tns:instrumentStateChangeMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13301" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="addComplexInstrumentMessage" type="tns:addComplexInstrumentMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13400" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="messageHeader_t">
    <xs:sequence>
      <xs:element name="bodyLen" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="templateId">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedShort">
            <xs:enumeration value="13001">
              <xs:annotation>
                <xs:documentation>Heartbeat Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13600">
              <xs:annotation>
                <xs:documentation>Product Summary Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13602">
              <xs:annotation>
                <xs:documentation>Snapshot Order Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13601">
              <xs:annotation>
                <xs:documentation>Instrument Summary Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13500">
              <xs:annotation>
                <xs:documentation>Auction Best Bid Offer Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13501">
              <xs:annotation>
                <xs:documentation>Auction Clearing Price Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13504">
              <xs:annotation>
                <xs:documentation>Top Of Book Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13100">
              <xs:annotation>
                <xs:documentation>Order Add Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13101">
              <xs:annotation>
                <xs:documentation>Order Modify Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13106">
              <xs:annotation>
                <xs:documentation>Order Modify Same Priority Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13102">
              <xs:annotation>
                <xs:documentation>Order Delete Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13103">
              <xs:annotation>
                <xs:documentation>Order Mass Delete Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13105">
              <xs:annotation>
                <xs:documentation>Partial Order Execution Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13104">
              <xs:annotation>
                <xs:documentation>Full Order Execution Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13200">
              <xs:annotation>
                <xs:documentation>Trade Reversal Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13202">
              <xs:annotation>
                <xs:documentation>Execution Summary Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13203">
              <xs:annotation>
                <xs:documentation>Instrument Info Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13204">
              <xs:annotation>
                <xs:documentation>Lpp Range Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13300">
              <xs:annotation>
                <xs:documentation>Product State Change Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13301">
              <xs:annotation>
                <xs:documentation>Instrument State Change Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13400">
              <xs:annotation>
                <xs:documentation>Add Complex Instrument Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="13002">
              <xs:annotation>
                <xs:documentation>Packet Header</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="msgSeqNum" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="heartbeatMessage_t">
    <xs:sequence>
      <xs:element name="lastMsgSeqNumProcessed" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad4" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="productSummaryMessage_t">
    <xs:sequence>
      <xs:element name="lastMsgSeqNumProcessed" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradingSessionId">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Day</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Morning</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Evening</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>Holiday</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="tradingSessionSubId">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Pre Trading</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Trading</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Closing</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Post Trading</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="6">
              <xs:annotation>
                <xs:documentation>Post Closing</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>Quiescent</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="tradSesStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Halted</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Open</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Closed</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="fastMarketIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>No</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Yes</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="snapshotOrderMessage_t">
    <xs:sequence>
      <xs:element name="orderDetails" type="tns:orderDetails_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderDetails_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimePriority" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="displayQty" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="side">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Buy</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Sell</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="instrumentSummaryMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastUpdateTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsExecutionTime" nillable="true" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="totNoOrders" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Active</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Inactive</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Expired</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="9">
              <xs:annotation>
                <xs:documentation>Suspended</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="securityTradingStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="200">
              <xs:annotation>
                <xs:documentation>Closed</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="201">
              <xs:annotation>
                <xs:documentation>Restricted</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="202">
              <xs:annotation>
                <xs:documentation>Book</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="203">
              <xs:annotation>
                <xs:documentation>Continuous</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="204">
              <xs:annotation>
                <xs:documentation>Opening Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="205">
              <xs:annotation>
                <xs:documentation>Opening Auction Freeze</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="206">
              <xs:annotation>
                <xs:documentation>Intraday Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="207">
              <xs:annotation>
                <xs:documentation>Intraday Auction Freeze</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="208">
              <xs:annotation>
                <xs:documentation>Circuit Breaker Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="209">
              <xs:annotation>
                <xs:documentation>Circuit Breaker Auction Freeze</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="210">
              <xs:annotation>
                <xs:documentation>Closing Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="211">
              <xs:annotation>
                <xs:documentation>Closing Auction Freeze</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="fastMarketIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>No</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Yes</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="noMdEntries" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeVolume" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="noOfTrades" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad4" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdInstrumentEntryGrp" type="tns:mdInstrumentEntryGrp_t" maxOccurs="unbounded">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element occursCountKind="expression" occursCount="{ ../noMdEntries }" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mdInstrumentEntryGrp_t">
    <xs:sequence>
      <xs:element name="mdEntryPx" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdEntrySize" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdEntryType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Opening Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Closing Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>High Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="8">
              <xs:annotation>
                <xs:documentation>Low Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="101">
              <xs:annotation>
                <xs:documentation>Previous Closing Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="200">
              <xs:annotation>
                <xs:documentation>Opening Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="201">
              <xs:annotation>
                <xs:documentation>Intraday Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="202">
              <xs:annotation>
                <xs:documentation>Circuit Breaker Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="203">
              <xs:annotation>
                <xs:documentation>Closing Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="204">
              <xs:annotation>
                <xs:documentation>Upper Ckt Limit</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="205">
              <xs:annotation>
                <xs:documentation>Lower Ckt Limit</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="206">
              <xs:annotation>
                <xs:documentation>Gross Trade Amt</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="208">
              <xs:annotation>
                <xs:documentation>Upper Exec Limit</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="209">
              <xs:annotation>
                <xs:documentation>Lower Exec Limit</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="auctionBestBidOfferMessage_t">
    <xs:sequence>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="bidPx" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="offerPx" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="auctionClearingPriceMessage_t">
    <xs:sequence>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="topOfBookMessage_t">
    <xs:sequence>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="bidPx" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="offerPx" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderAddMessage_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimeIn" nillable="true" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderDetails" type="tns:orderDetails_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderModifyMessage_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimeIn" nillable="true" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsPrevTimePriority" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="prevPrice" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="prevDisplayQty" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderDetails" type="tns:orderDetails_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderModifySamePriorityMessage_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimeIn" nillable="true" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="prevDisplayQty" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderDetails" type="tns:orderDetails_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderDeleteMessage_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimeIn" nillable="true" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderDetails" type="tns:orderDetails_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderMassDeleteMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="partialOrderExecutionMessage_t">
    <xs:sequence>
      <xs:element name="side">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Buy</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Sell</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsTimePriority" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdMatchId" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad4" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fullOrderExecutionMessage_t">
    <xs:sequence>
      <xs:element name="side">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Buy</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Sell</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsTimePriority" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdMatchId" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad4" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradeReversalMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdMatchId" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad4" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsExecutionTime" nillable="true" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="noMdEntries" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdTradeEntryGrp" type="tns:mdTradeEntryGrp_t" maxOccurs="unbounded">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element occursCountKind="expression" occursCount="{ ../noMdEntries }" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mdTradeEntryGrp_t">
    <xs:sequence>
      <xs:element name="mdEntryPx" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdEntrySize" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdEntryType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Opening Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Closing Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>High Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="8">
              <xs:annotation>
                <xs:documentation>Low Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="101">
              <xs:annotation>
                <xs:documentation>Previous Closing Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="200">
              <xs:annotation>
                <xs:documentation>Opening Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="201">
              <xs:annotation>
                <xs:documentation>Intraday Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="202">
              <xs:annotation>
                <xs:documentation>Circuit Breaker Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="203">
              <xs:annotation>
                <xs:documentation>Closing Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="204">
              <xs:annotation>
                <xs:documentation>Upper Ckt Limit</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="205">
              <xs:annotation>
                <xs:documentation>Lower Ckt Limit</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="206">
              <xs:annotation>
                <xs:documentation>Gross Trade Amt</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="208">
              <xs:annotation>
                <xs:documentation>Upper Exec Limit</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="209">
              <xs:annotation>
                <xs:documentation>Lower Exec Limit</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="executionSummaryMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="aggressorTimestamp" nillable="true" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="execId" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="aggressorSide">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Buy</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Sell</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="tradeCondition" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="255" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Implied Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pad6" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="restingHiddenQty" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="instrumentInfoMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="closePrice" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="prevClosePrice" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="upperCktLimit" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lowerCktLimit" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="lppRangeMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="upperExecLimit" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lowerExecLimit" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="productStateChangeMessage_t">
    <xs:sequence>
      <xs:element name="tradingSessionId">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Day</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Morning</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Evening</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>Holiday</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="tradingSessionSubId">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Pre Trading</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Trading</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Closing</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Post Trading</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="6">
              <xs:annotation>
                <xs:documentation>Post Closing</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>Quiescent</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="tradSesStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Halted</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Open</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Closed</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="fastMarketIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>No</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Yes</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pad4" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="instrumentStateChangeMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Active</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Inactive</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Expired</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="9">
              <xs:annotation>
                <xs:documentation>Suspended</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="securityTradingStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="200">
              <xs:annotation>
                <xs:documentation>Closed</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="201">
              <xs:annotation>
                <xs:documentation>Restricted</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="202">
              <xs:annotation>
                <xs:documentation>Book</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="203">
              <xs:annotation>
                <xs:documentation>Continuous</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="204">
              <xs:annotation>
                <xs:documentation>Opening Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="205">
              <xs:annotation>
                <xs:documentation>Opening Auction Freeze</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="206">
              <xs:annotation>
                <xs:documentation>Intraday Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="207">
              <xs:annotation>
                <xs:documentation>Intraday Auction Freeze</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="208">
              <xs:annotation>
                <xs:documentation>Circuit Breaker Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="209">
              <xs:annotation>
                <xs:documentation>Circuit Breaker Auction Freeze</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="210">
              <xs:annotation>
                <xs:documentation>Closing Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="211">
              <xs:annotation>
                <xs:documentation>Closing Auction Freeze</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="fastMarketIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>No</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Yes</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pad5" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="5" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="addComplexInstrumentMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securitySubType" nillable="true" type="xs:int">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="-2147483648" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="productComplex">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Futures Spread</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="impliedMarketIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>Not Implied</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Implied In Out</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="noLegs" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad1" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="instrmtLegGrp" type="tns:instrmtLegGrp_t" maxOccurs="unbounded">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element occursCountKind="expression" occursCount="{ ../noLegs }" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="instrmtLegGrp_t">
    <xs:sequence>
      <xs:element name="legSecurityId" type="xs:long">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="legRatioQty" nillable="true" type="xs:int">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="-2147483648" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="legSide">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Buy</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Sell</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="pad3" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="3" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>