<?xml version="1.0" encoding="UTF-8"?>
<!--
  Dfdl schema definition for: Miax MiaxOptions Mpf v1.1

  Protocol:
    Organization: Miami International Holdings
    Protocol: MIAX Product Feed
    Encoding: Mach
    Version: 1.1
    Date: 02/20/2019
    Specification: MIAX_Product_Feed_v1.1_re.pdf

  Script:
    Generator: 1.0.0.0
    License: Public/GPLv3
    Authors: Omi Developers

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under
  the license noted above.

  The protocol compiler technologies used to produce this file
  are the subject of patents owned by Scaled Sources LLC.  Those patent
  rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en

  Open Markets Initiative website:
    https://openmarketsinitiative.com
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:tns="urn:omi:miaxoptions:mpf:v1:1" targetNamespace="urn:omi:miaxoptions:mpf:v1:1">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="littleEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="udpPacket" type="tns:udpPacket_t" />
  <xs:element name="tcpPacket" type="tns:tcpPacket_t" />
  <xs:complexType name="udpPacket_t">
    <xs:sequence>
      <xs:element name="machMessage" type="tns:machMessage_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="machMessage_t">
    <xs:sequence>
      <xs:element name="sequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="packetLength" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="packetType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>Heartbeat</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Start Of Session</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>End Of Session</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Application Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="sessionNumber" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="payload" type="tns:applicationMessage_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="applicationMessage_t">
    <xs:sequence>
      <xs:element name="messageType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>System Time Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="s">
              <xs:annotation>
                <xs:documentation>Symbol Definition Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="I">
              <xs:annotation>
                <xs:documentation>Index Value Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Z">
              <xs:annotation>
                <xs:documentation>Synthetic Future Value Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="data">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../../../packetLength - 12 - 1 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../messageType) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="systemTimeMessage" type="tns:systemTimeMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="1" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="symbolDefinitionMessage" type="tns:symbolDefinitionMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="s" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="indexValueMessage" type="tns:indexValueMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="I" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="syntheticFutureValueMessage" type="tns:syntheticFutureValueMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="Z" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="systemTimeMessage_t">
    <xs:sequence>
      <xs:element name="seconds" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="symbolDefinitionMessage_t">
    <xs:sequence>
      <xs:element name="nanoseconds" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="syntheticFutureSymbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="settlementDate" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbolStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Active Future</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="I">
              <xs:annotation>
                <xs:documentation>Inactive Future</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="reserved16" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="16" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="indexValueMessage_t">
    <xs:sequence>
      <xs:element name="nanoseconds" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="5" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="value" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="syntheticFutureValueMessage_t">
    <xs:sequence>
      <xs:element name="nanoseconds" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="syntheticFutureSymbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="value" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved8" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tcpPacket_t">
    <xs:sequence>
      <xs:element name="sesmTcpPacket" type="tns:sesmTcpPacket_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="sesmTcpPacket_t">
    <xs:sequence>
      <xs:element name="sesmPacketHeader" type="tns:sesmPacketHeader_t" />
      <xs:element name="sesmPayload">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../sesmPacketHeader/sesmPacketLength + 2 - 3 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../sesmPacketHeader/sesmPacketType) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="sequencedDataPacket" type="tns:sequencedDataPacket_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="s" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="unsequencedDataPacket" type="tns:unsequencedDataPacket_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="U" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="loginRequest" type="tns:loginRequest_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="l" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="loginResponse" type="tns:loginResponse_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="r" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="synchronizationComplete" type="tns:synchronizationComplete_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="c" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="retransmissionRequest" type="tns:retransmissionRequest_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="a" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="logoutRequest" type="tns:logoutRequest_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="X" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="goodbyePacket" type="tns:goodbyePacket_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="G" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradingSessionUpdate">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="u" />
                </xs:appinfo>
              </xs:annotation>
              <xs:complexType>
                <xs:sequence />
              </xs:complexType>
            </xs:element>
            <xs:element name="serverHeartbeat">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="0" />
                </xs:appinfo>
              </xs:annotation>
              <xs:complexType>
                <xs:sequence />
              </xs:complexType>
            </xs:element>
            <xs:element name="clientHeartbeat">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="1" />
                </xs:appinfo>
              </xs:annotation>
              <xs:complexType>
                <xs:sequence />
              </xs:complexType>
            </xs:element>
            <xs:element name="testPacket" type="tns:testPacket_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="T" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="sesmPacketHeader_t">
    <xs:sequence>
      <xs:element name="sesmPacketLength" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="sesmPacketType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="s">
              <xs:annotation>
                <xs:documentation>Sequenced Data Packet</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="U">
              <xs:annotation>
                <xs:documentation>Unsequenced Data Packet</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="l">
              <xs:annotation>
                <xs:documentation>Login Request</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="r">
              <xs:annotation>
                <xs:documentation>Login Response</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="c">
              <xs:annotation>
                <xs:documentation>Synchronization Complete</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="a">
              <xs:annotation>
                <xs:documentation>Retransmission Request</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="X">
              <xs:annotation>
                <xs:documentation>Logout Request</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="G">
              <xs:annotation>
                <xs:documentation>Goodbye Packet</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="u">
              <xs:annotation>
                <xs:documentation>Trading Session Update</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>Server Heartbeat</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Client Heartbeat</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="T">
              <xs:annotation>
                <xs:documentation>Test Packet</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="sequencedDataPacket_t">
    <xs:sequence>
      <xs:element name="sequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="matchingEngineId" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="sequencedMessageType" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="unsequencedDataPacket_t">
    <xs:sequence>
      <xs:element name="unsequencedMessageType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="R">
              <xs:annotation>
                <xs:documentation>Refresh Request Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="r">
              <xs:annotation>
                <xs:documentation>Refresh Response Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="E">
              <xs:annotation>
                <xs:documentation>End Of Refresh Notification Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="unsequencedMessage">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../../../sesmPacketHeader/sesmPacketLength - 2 - 1 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../unsequencedMessageType) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="refreshRequestMessage" type="tns:refreshRequestMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="R" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="refreshResponseMessage" type="tns:refreshResponseMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="r" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="endOfRefreshNotificationMessage" type="tns:endOfRefreshNotificationMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="E" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="refreshRequestMessage_t">
    <xs:sequence>
      <xs:element name="refreshMessageType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="I">
              <xs:annotation>
                <xs:documentation>Index Update Refresh</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Z">
              <xs:annotation>
                <xs:documentation>Synthetic Future Values</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="refreshResponseMessage_t">
    <xs:sequence>
      <xs:element name="sequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="applicationMessage" type="tns:applicationMessage_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="endOfRefreshNotificationMessage_t">
    <xs:sequence>
      <xs:element name="refreshMessageType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="I">
              <xs:annotation>
                <xs:documentation>Index Update Refresh</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Z">
              <xs:annotation>
                <xs:documentation>Synthetic Future Values</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="loginRequest_t">
    <xs:sequence>
      <xs:element name="sesmVersion" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="5" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="username" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="5" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="computerId" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="applicationProtocol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="requestedTradingSessionId" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="requestedSequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="loginResponse_t">
    <xs:sequence>
      <xs:element name="numberOfMatchingEngines" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="loginStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Successful</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="S">
              <xs:annotation>
                <xs:documentation>Invalid Trading Session Requested</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="U">
              <xs:annotation>
                <xs:documentation>No Active Trading Session Exists</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="X">
              <xs:annotation>
                <xs:documentation>Rejected</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Invalid Start Sequence Number Requested</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="I">
              <xs:annotation>
                <xs:documentation>Incompatible Session Protocol Version</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Incompatible Application Protocol Version</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="L">
              <xs:annotation>
                <xs:documentation>Request Rejected Because Client Already Logged In</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="tradingSessionId" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="highestSequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="synchronizationComplete_t">
    <xs:sequence>
      <xs:element name="numberOfMatchingEngines" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="retransmissionRequest_t">
    <xs:sequence>
      <xs:element name="startSequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="endSequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="logoutRequest_t">
    <xs:sequence>
      <xs:element name="logoutReason">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Graceful Logout</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="B">
              <xs:annotation>
                <xs:documentation>Bad Packet</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="L">
              <xs:annotation>
                <xs:documentation>Timed Out</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Application Terminating Connection</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="logoutText" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="0" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="goodbyePacket_t">
    <xs:sequence>
      <xs:element name="logoutReason">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Graceful Logout</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="B">
              <xs:annotation>
                <xs:documentation>Bad Packet</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="L">
              <xs:annotation>
                <xs:documentation>Timed Out</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Application Terminating Connection</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="logoutText" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="0" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="testPacket_t">
    <xs:sequence>
      <xs:element name="testText" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="0" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>