<?xml version="1.0" encoding="UTF-8"?>
<!--
  Dfdl schema definition for: Eurex T7 Eti v1

  Protocol:
    Organization: Eurex Exchange
    Protocol: Enhanced Trading Interface
    Encoding: Flat Binary Encoding
    Version: 1
    Date: 01/1/2015
    Specification: Unknown

  Script:
    Generator: 1.0.0.0
    License: Public/GPLv3
    Authors: Omi Developers

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under
  the license noted above.

  The protocol compiler technologies used to produce this file
  are the subject of patents owned by Scaled Sources LLC.  Those patent
  rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en

  Open Markets Initiative website:
    https://openmarketsinitiative.com
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:tns="urn:omi:eurex:t7:eti:v1" targetNamespace="urn:omi:eurex:t7:eti:v1">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="littleEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="clientPacket" type="tns:clientPacket_t" />
  <xs:element name="serverPacket" type="tns:serverPacket_t" />
  <xs:complexType name="clientPacket_t">
    <xs:sequence>
      <xs:element name="clientMessage" type="tns:clientMessage_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="clientMessage_t">
    <xs:sequence>
      <xs:element name="messageHeader" type="tns:messageHeader_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="messageHeader_t">
    <xs:sequence>
      <xs:element name="bodyLen" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="templateId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="serverPacket_t">
    <xs:sequence>
      <xs:element name="serverMessage" type="tns:serverMessage_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="serverMessage_t">
    <xs:sequence>
      <xs:element name="messageHeader" type="tns:messageHeader_t" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>