<?xml version="1.0" encoding="UTF-8"?>
<!--
  Dfdl schema definition for: Cboe BzxEquities SummaryDepth v1.0.4

  Protocol:
    Organization: Chicago Board Options Exchange
    Protocol: Summary Depth
    Encoding: Pitch
    Version: 1.0.4
    Date: 7/26/2021
    Specification: Cboe_US_Equities_Summary_Depth_Feed_Specification.pdf

  Script:
    Generator: 1.0.0.0
    License: Public/GPLv3
    Authors: Omi Developers

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under
  the license noted above.

  The protocol compiler technologies used to produce this file
  are the subject of patents owned by Scaled Sources LLC.  Those patent
  rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en

  Open Markets Initiative website:
    https://openmarketsinitiative.com
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:tns="urn:omi:bzxequities:summarydepth:v1:0:4" targetNamespace="urn:omi:bzxequities:summarydepth:v1:0:4">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="littleEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="packet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="packetHeader" type="tns:packetHeader_t" />
        <xs:element name="messages" type="tns:message_t" maxOccurs="unbounded">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element occursCountKind="expression" occursCount="{ ../packetHeader/count }" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="packetHeader_t">
    <xs:sequence>
      <xs:element name="length" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="count" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="unit" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="sequence" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="message_t">
    <xs:sequence>
      <xs:element name="messageHeader" type="tns:messageHeader_t" />
      <xs:element name="payload">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../messageHeader/messageLength - 2 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../messageHeader/messageType) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="clearQuoteMessage" type="tns:clearQuoteMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="162" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="cboeMarketStatusMessage" type="tns:cboeMarketStatusMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="166" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="adapMessage" type="tns:adapMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="167" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="rpiMessage" type="tns:rpiMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="168" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradeMessage" type="tns:tradeMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="169" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradeBreakMessage" type="tns:tradeBreakMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="170" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradingStatusMessage" type="tns:tradingStatusMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="171" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="messageHeader_t">
    <xs:sequence>
      <xs:element name="messageLength" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="messageType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="162">
              <xs:annotation>
                <xs:documentation>Clear Quote Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="166">
              <xs:annotation>
                <xs:documentation>Cboe Market Status Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="167">
              <xs:annotation>
                <xs:documentation>Adap Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="168">
              <xs:annotation>
                <xs:documentation>Rpi Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="169">
              <xs:annotation>
                <xs:documentation>Trade Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="170">
              <xs:annotation>
                <xs:documentation>Trade Break Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="171">
              <xs:annotation>
                <xs:documentation>Trading Status Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="clearQuoteMessage_t">
    <xs:sequence>
      <xs:element name="lastUpdateTimestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved1" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="cboeMarketStatusMessage_t">
    <xs:sequence>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved1" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Normal</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="E">
              <xs:annotation>
                <xs:documentation>Excluded From Adap Updates</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="I">
              <xs:annotation>
                <xs:documentation>Incomplete</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="sessionIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="R">
              <xs:annotation>
                <xs:documentation>Regular Trading Session</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="P">
              <xs:annotation>
                <xs:documentation>Pre Or Post Market Session</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="adapMessage_t">
    <xs:sequence>
      <xs:element name="lastUpdateTimestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="adapFlags" type="tns:adapFlags_t" />
      <xs:element name="reserved1" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="adapBlocks" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="adapBlock" type="tns:adapBlock_t" maxOccurs="unbounded">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element occursCountKind="expression" occursCount="{ ../adapBlocks }" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="adapFlags_t">
    <xs:sequence>
      <xs:element name="clear" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" bitOrder="leastSignificantBitFirst" byteOrder="littleEndian" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="complete" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" bitOrder="leastSignificantBitFirst" byteOrder="littleEndian" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="blockType" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" bitOrder="leastSignificantBitFirst" byteOrder="littleEndian" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="unused5" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" bitOrder="leastSignificantBitFirst" byteOrder="littleEndian" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="5" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="adapBlock_t">
    <xs:sequence>
      <xs:element name="adapBlockSize" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="adapUpdate">
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../adapBlockSize) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="shortUpdateAdapBlock" type="tns:shortUpdateAdapBlock_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="10" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="longUpdateAdapBlock" type="tns:longUpdateAdapBlock_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="18" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="shortUpdateAdapBlock_t">
    <xs:sequence>
      <xs:element name="side" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="priceShort" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="quantityShort" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="longUpdateAdapBlock_t">
    <xs:sequence>
      <xs:element name="side" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="priceLong" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="quantityLong" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="rpiMessage_t">
    <xs:sequence>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved1" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="retailPriceImprovement">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="B">
              <xs:annotation>
                <xs:documentation>Buy Side Rpi</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="S">
              <xs:annotation>
                <xs:documentation>Sell Side Rpi</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Buy And Sell Rpi</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>No Rpi</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradeMessage_t">
    <xs:sequence>
      <xs:element name="transactionTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved1" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="executionId" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPrice" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQuantity" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="cboeCumulativeExecutedVolume" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved8" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeFlags" type="tns:tradeFlags_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradeFlags_t">
    <xs:sequence>
      <xs:element name="unused1" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" bitOrder="leastSignificantBitFirst" byteOrder="littleEndian" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastsaleEligible" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" bitOrder="leastSignificantBitFirst" byteOrder="littleEndian" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="unused6" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" bitOrder="leastSignificantBitFirst" byteOrder="littleEndian" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradeBreakMessage_t">
    <xs:sequence>
      <xs:element name="transactionTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved1" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="executionId" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="cboeCumulativeExecutedVolume" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved8" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeBreakFlags" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradingStatusMessage_t">
    <xs:sequence>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="symbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved1" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="haltStatus" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="regShoAction">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>No Price Test In Effect</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Reg Sho Price Test Restriction In Effect</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>