<?xml version="1.0" encoding="UTF-8"?>
<!--
  Dfdl schema definition for: Osi Network Transport v1

  Protocol:
    Organization: Open Systems Interconnection
    Protocol: Transport
    Encoding: Transmission Control Protocol
    Version: 1
    Date: 10/5/2026
    Specification: Unknown

  Script:
    Generator: 1.0.0.0
    License: Public/GPLv3
    Authors: Omi Developers

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under
  the license noted above.

  The protocol compiler technologies used to produce this file
  are the subject of patents owned by Scaled Sources LLC.  Those patent
  rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en

  Open Markets Initiative website:
    https://openmarketsinitiative.com
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:tns="urn:omi:osi:network:transport:v1" targetNamespace="urn:omi:osi:network:transport:v1">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="bigEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="packet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tcpSourcePort" type="xs:unsignedShort">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
        <xs:element name="tcpDestinationPort" type="xs:unsignedShort">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
        <xs:element name="tcpSequenceNumber" type="xs:unsignedInt">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
        <xs:element name="acknowledgmentNumber" type="xs:unsignedInt">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
        <xs:element name="offsetAndFlags" type="tns:offsetAndFlags_t" />
        <xs:element name="windowSize" type="xs:unsignedShort">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
        <xs:element name="tcpChecksum" type="xs:unsignedShort">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
        <xs:element name="urgentPointer" type="xs:unsignedShort">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
        <xs:element name="tcpOptions" type="xs:hexBinary">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element representation="binary" lengthKind="explicit" length="0" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
        <xs:element name="tcpPayload" type="xs:hexBinary">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element lengthKind="pattern" lengthPattern="(?s).*" encoding="ISO-8859-1" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="offsetAndFlags_t">
    <xs:sequence>
      <xs:element name="finFlag" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="synFlag" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="rstFlag" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pshFlag" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ackFlag" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="urgFlag" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="eceFlag" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="cwrFlag" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="nsFlag" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tcpReserved" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="3" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="dataOffset" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>