<?xml version="1.0" encoding="UTF-8"?>
<!--
  Dfdl schema definition for: Nasdaq PsxEquities Bbo v2.1.2018

  Protocol:
    Organization: National Association of Securities Dealers Automated Quotations (Nasdaq)
    Protocol: Best Bid And Offer
    Encoding: Itch
    Version: 2.1.2018
    Date: 05/03/2018
    Specification: PSXbboSpecification2.1.pdf

  Script:
    Generator: 1.0.0.0
    License: Public/GPLv3
    Authors: Omi Developers

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under
  the license noted above.

  The protocol compiler technologies used to produce this file
  are the subject of patents owned by Scaled Sources LLC.  Those patent
  rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en

  Open Markets Initiative website:
    https://openmarketsinitiative.com
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:tns="urn:omi:psxequities:bbo:v2:1:2018" targetNamespace="urn:omi:psxequities:bbo:v2:1:2018">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="bigEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="packet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="packetHeader" type="tns:packetHeader_t" />
        <xs:element name="messages" type="tns:message_t" maxOccurs="unbounded">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element occursCountKind="expression" occursCount="{ ../packetHeader/messageCount }" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="packetHeader_t">
    <xs:sequence>
      <xs:element name="session" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="10" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="sequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="messageCount" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="message_t">
    <xs:sequence>
      <xs:element name="messageHeader" type="tns:messageHeader_t" />
      <xs:element name="payload">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../messageHeader/messageLength - 1 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../messageHeader/messageType) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="systemEventMessage" type="tns:systemEventMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="S" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="stockDirectoryMessage" type="tns:stockDirectoryMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="R" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="stockTradingActionMessage" type="tns:stockTradingActionMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="H" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="regShoShortSalePriceTestRestrictedIndicatorMessage" type="tns:regShoShortSalePriceTestRestrictedIndicatorMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="Y" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="mwcbDeclineLevelMessage" type="tns:mwcbDeclineLevelMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="V" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="mwcbStatusMessage" type="tns:mwcbStatusMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="W" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="operationalHaltMessage" type="tns:operationalHaltMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="h" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="quotationMessage" type="tns:quotationMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="Q" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="nextSharesQuotationMessage" type="tns:nextSharesQuotationMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="A" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="messageHeader_t">
    <xs:sequence>
      <xs:element name="messageLength" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="messageType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="S">
              <xs:annotation>
                <xs:documentation>System Event Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="R">
              <xs:annotation>
                <xs:documentation>Stock Directory Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="H">
              <xs:annotation>
                <xs:documentation>Stock Trading Action Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Y">
              <xs:annotation>
                <xs:documentation>Reg Sho Short Sale Price Test Restricted Indicator Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="V">
              <xs:annotation>
                <xs:documentation>Mwcb Decline Level Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="W">
              <xs:annotation>
                <xs:documentation>Mwcb Status Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="h">
              <xs:annotation>
                <xs:documentation>Operational Halt Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Q">
              <xs:annotation>
                <xs:documentation>Quotation Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Next Shares Quotation Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="systemEventMessage_t">
    <xs:sequence>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="eventCode">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="O">
              <xs:annotation>
                <xs:documentation>Start Of Transmissions</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="S">
              <xs:annotation>
                <xs:documentation>Start Of System Hours</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Q">
              <xs:annotation>
                <xs:documentation>Start Of Market Hours</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="M">
              <xs:annotation>
                <xs:documentation>End Of Market Hours</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="E">
              <xs:annotation>
                <xs:documentation>End Of System Hours</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="C">
              <xs:annotation>
                <xs:documentation>End Of Messages</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="stockDirectoryMessage_t">
    <xs:sequence>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketCategory">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Q">
              <xs:annotation>
                <xs:documentation>Nasdaq Global Select Market</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="G">
              <xs:annotation>
                <xs:documentation>Nasdaq Global Market</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="S">
              <xs:annotation>
                <xs:documentation>Nasdaq Capital Market</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Nyse</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Nyse Amex</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="P">
              <xs:annotation>
                <xs:documentation>Nyse Arca</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Z">
              <xs:annotation>
                <xs:documentation>Bats Bzx</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="V">
              <xs:annotation>
                <xs:documentation>Investors Exchange</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Na</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="financialStatusIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="D">
              <xs:annotation>
                <xs:documentation>Deficient</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="E">
              <xs:annotation>
                <xs:documentation>Delinquent</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Q">
              <xs:annotation>
                <xs:documentation>Bankrupt</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="S">
              <xs:annotation>
                <xs:documentation>Suspended</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="G">
              <xs:annotation>
                <xs:documentation>Deficient And Bankrupt</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="H">
              <xs:annotation>
                <xs:documentation>Deficient And Delinquent</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="J">
              <xs:annotation>
                <xs:documentation>Delinquent And Bankrupt</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="K">
              <xs:annotation>
                <xs:documentation>Deficient Delinquent And Bankrupt</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="C">
              <xs:annotation>
                <xs:documentation>Creations And Redemptions Suspended</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Normal</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Na</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="roundLotSize" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="roundLotsOnly">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Y">
              <xs:annotation>
                <xs:documentation>Round Lots Only</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Odd Mixed Allowed</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="issueClassification" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="issueSubType" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="authenticity">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="P">
              <xs:annotation>
                <xs:documentation>Live Production</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="T">
              <xs:annotation>
                <xs:documentation>Test</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="shortSaleThresholdIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Y">
              <xs:annotation>
                <xs:documentation>Restricted</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Not Restricted</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Na</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ipoFlag">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Y">
              <xs:annotation>
                <xs:documentation>Nasdaq Listed Instrument</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Nasdaq Listed Instrument</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Na</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="luldReferencePriceTier">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Tier 1</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Tier 2</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Na</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="etpFlag">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Y">
              <xs:annotation>
                <xs:documentation>Etp</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Not Etp</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Na</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="etpLeverageFactor" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="inverseIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Y">
              <xs:annotation>
                <xs:documentation>Inverse Etp</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Not Inverse Etp</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="stockTradingActionMessage_t">
    <xs:sequence>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityClass">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Q">
              <xs:annotation>
                <xs:documentation>Nasdaq Listed Issue</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Nyse</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Nyse Mkt</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="P">
              <xs:annotation>
                <xs:documentation>Nyse Arca</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Z">
              <xs:annotation>
                <xs:documentation>Bats</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="V">
              <xs:annotation>
                <xs:documentation>Iexg</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Na</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="currentTradingState">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="H">
              <xs:annotation>
                <xs:documentation>Halted</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="P">
              <xs:annotation>
                <xs:documentation>Paused</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Q">
              <xs:annotation>
                <xs:documentation>Quotation Only Period</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="T">
              <xs:annotation>
                <xs:documentation>Trading</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="reason" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="regShoShortSalePriceTestRestrictedIndicatorMessage_t">
    <xs:sequence>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="regShoAction">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>No Price Test</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Reg Sho Short Sale Price Test Restriction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Test Restriction Remains</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mwcbDeclineLevelMessage_t">
    <xs:sequence>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="level1" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="level2" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="level3" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mwcbStatusMessage_t">
    <xs:sequence>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="breachedLevel">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Level 1</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Level 2</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Level 3</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="operationalHaltMessage_t">
    <xs:sequence>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketCode">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Q">
              <xs:annotation>
                <xs:documentation>Nasdaq</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="B">
              <xs:annotation>
                <xs:documentation>Bx</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="X">
              <xs:annotation>
                <xs:documentation>Psx</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="operationalHaltAction">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="H">
              <xs:annotation>
                <xs:documentation>Halted</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="T">
              <xs:annotation>
                <xs:documentation>Resumed</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="quotationMessage_t">
    <xs:sequence>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityClass">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Q">
              <xs:annotation>
                <xs:documentation>Nasdaq Listed Issue</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Nyse</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Nyse Mkt</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="P">
              <xs:annotation>
                <xs:documentation>Nyse Arca</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Z">
              <xs:annotation>
                <xs:documentation>Bats</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="V">
              <xs:annotation>
                <xs:documentation>Iexg</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Na</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="psxBestBidPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="psxBestBidSize" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="psxBestOfferPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="psxBestOfferSize" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="nextSharesQuotationMessage_t">
    <xs:sequence>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="nextSharesSymbol" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityClass">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Q">
              <xs:annotation>
                <xs:documentation>Nasdaq Listed Issue</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="N">
              <xs:annotation>
                <xs:documentation>Nyse</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Nyse Mkt</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="P">
              <xs:annotation>
                <xs:documentation>Nyse Arca</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="Z">
              <xs:annotation>
                <xs:documentation>Bats</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="V">
              <xs:annotation>
                <xs:documentation>Iexg</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value=" ">
              <xs:annotation>
                <xs:documentation>Na</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="nasdaqBestBid" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>