<?xml version="1.0" encoding="UTF-8"?>
<!--
  Dfdl schema definition for: Eurex T7 Eobi v8.0

  Protocol:
    Organization: Eurex Exchange
    Protocol: Enhanced Order Book Interface
    Encoding: Flat Binary Encoding
    Version: 8.0
    Date: 9/23/2019
    Specification: T7_EOBI_Manual_v.8.0.1.pdf

  Script:
    Generator: 1.0.0.0
    License: Public/GPLv3
    Authors: Omi Developers

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under
  the license noted above.

  The protocol compiler technologies used to produce this file
  are the subject of patents owned by Scaled Sources LLC.  Those patent
  rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en

  For full Omi information:
    https://github.com/Open-Markets-Initiative/Directory

  Open Markets Initiative website:
    https://openmarketsinitiative.com
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:tns="urn:omi:eurex:t7:eobi:v8:0" targetNamespace="urn:omi:eurex:t7:eobi:v8:0">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="littleEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="packet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="packetHeader" type="tns:packetHeader_t" />
        <xs:element name="message" type="tns:message_t" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="packetHeader_t">
    <xs:sequence>
      <xs:element name="eobiHeader" type="tns:eobiHeader_t" />
      <xs:element name="applSeqNum" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketSegmentId" type="xs:int" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0x80000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="partitionId" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="completionIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="applSeqResetIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad1" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="eobiHeader_t">
    <xs:sequence>
      <xs:element name="bodyLen" type="xs:unsignedShort" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" nilKind="literalValue" nilValue="0xFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="templateId" type="xs:unsignedShort" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" nilKind="literalValue" nilValue="0xFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="msgSeqNum" type="xs:unsignedInt" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0xFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="message_t">
    <xs:sequence>
      <xs:element name="messageHeaderComp" type="tns:messageHeaderComp_t" />
      <xs:element name="payload">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../messageHeaderComp/bodyLen - 8 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../messageHeaderComp/templateId) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="addComplexInstrument" type="tns:addComplexInstrument_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13400" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="auctionBbo" type="tns:auctionBbo_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13500" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="auctionClearingPrice" type="tns:auctionClearingPrice_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13501" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="crossRequest" type="tns:crossRequest_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13502" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="executionSummary" type="tns:executionSummary_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13202" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="fullOrderExecution" type="tns:fullOrderExecution_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13104" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="heartbeat" type="tns:heartbeat_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13001" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="instrumentStateChange" type="tns:instrumentStateChange_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13301" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="instrumentSummary" type="tns:instrumentSummary_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13601" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="massInstrumentStateChange" type="tns:massInstrumentStateChange_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13302" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderAdd" type="tns:orderAdd_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13100" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderDelete" type="tns:orderDelete_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13102" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderMassDelete" type="tns:orderMassDelete_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13103" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderModify" type="tns:orderModify_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13101" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderModifySamePrio" type="tns:orderModifySamePrio_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13106" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="partialOrderExecution" type="tns:partialOrderExecution_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13105" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="productStateChange" type="tns:productStateChange_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13300" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="productSummary" type="tns:productSummary_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13600" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="quoteRequest" type="tns:quoteRequest_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13503" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="snapshotOrder" type="tns:snapshotOrder_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13602" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="topOfBook" type="tns:topOfBook_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13504" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradeReport" type="tns:tradeReport_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13201" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradeReversal" type="tns:tradeReversal_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="13200" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="messageHeaderComp_t">
    <xs:sequence>
      <xs:element name="bodyLen" type="xs:unsignedShort" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" nilKind="literalValue" nilValue="0xFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="templateId" type="xs:unsignedShort" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" nilKind="literalValue" nilValue="0xFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="msgSeqNum" type="xs:unsignedInt" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0xFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="addComplexInstrument_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securitySubType" type="xs:int" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0x80000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="productComplex" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="impliedMarketIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="noLegs" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad1" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="instrmtLegGrpComp" type="tns:instrmtLegGrpComp_t" maxOccurs="unbounded">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element occursCountKind="expression" occursCount="{ ../noLegs }" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="instrmtLegGrpComp_t">
    <xs:sequence>
      <xs:element name="legSymbol" type="xs:int" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0x80000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad4" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="legSecurityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="legPrice" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="legRatioQty" type="xs:int" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0x80000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="legSecurityType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="legSide" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad2" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="auctionBbo_t">
    <xs:sequence>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="bidPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="offerPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="bidSize" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="offerSize" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="potentialSecurityTradingEvent" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="bidOrdType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="offerOrdType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad1" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="auctionClearingPrice_t">
    <xs:sequence>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="imbalanceQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityTradingStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="potentialSecurityTradingEvent" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad6" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="crossRequest_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="side" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="crossRequestType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="inputSource" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad1" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="executionSummary_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="aggressorTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="requestTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="execId" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="aggressorSide" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad6" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="restingHiddenQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="restingCxlQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fullOrderExecution_t">
    <xs:sequence>
      <xs:element name="side" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ordType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="algorithmicTradeIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad1" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdMatchId" type="xs:unsignedInt" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0xFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsTimePriority" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="heartbeat_t">
    <xs:sequence>
      <xs:element name="lastMsgSeqNumProcessed" type="xs:unsignedInt" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0xFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad4" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="instrumentStateChange_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityTradingStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="fastMarketIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityTradingEvent" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="soldOutIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad2" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="instrumentSummary_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastUpdateTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsExecutionTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="totNoOrders" type="xs:unsignedShort" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" nilKind="literalValue" nilValue="0xFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityTradingStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="fastMarketIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityTradingEvent" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="soldOutIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="noMdEntries" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdInstrumentEntryGrpComp" type="tns:mdInstrumentEntryGrpComp_t" maxOccurs="unbounded">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element occursCountKind="expression" occursCount="{ ../noMdEntries }" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mdInstrumentEntryGrpComp_t">
    <xs:sequence>
      <xs:element name="mdEntryPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdEntrySize" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdEntryType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad6" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="massInstrumentStateChange_t">
    <xs:sequence>
      <xs:element name="instrumentScopeProductComplex" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityMassStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityMassTradingStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="massMarketCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="fastMarketIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityMassTradingEvent" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="massSoldOutIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad1" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastFragment" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="noRelatedSym" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad6" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="secMassStatGrpComp" type="tns:secMassStatGrpComp_t" maxOccurs="unbounded">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element occursCountKind="expression" occursCount="{ ../noRelatedSym }" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="secMassStatGrpComp_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityTradingStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityTradingEvent" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="soldOutIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad3" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="3" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderAdd_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimeIn" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderDetailsComp" type="tns:orderDetailsComp_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderDetailsComp_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimePriority" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="displayQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="side" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ordType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad6" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderDelete_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimeIn" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderDetailsComp" type="tns:orderDetailsComp_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderMassDelete_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderModify_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimeIn" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsPrevTimePriority" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="prevPrice" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="prevDisplayQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderDetailsComp" type="tns:orderDetailsComp_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderModifySamePrio_t">
    <xs:sequence>
      <xs:element name="trdRegTsTimeIn" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="prevDisplayQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderDetailsComp" type="tns:orderDetailsComp_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="partialOrderExecution_t">
    <xs:sequence>
      <xs:element name="side" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ordType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="algorithmicTradeIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad1" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdMatchId" type="xs:unsignedInt" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0xFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsTimePriority" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="productStateChange_t">
    <xs:sequence>
      <xs:element name="tradingSessionId" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradingSessionSubId" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradSesStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="fastMarketIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad3" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="3" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="productSummary_t">
    <xs:sequence>
      <xs:element name="lastMsgSeqNumProcessed" type="xs:unsignedInt" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0xFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradingSessionId" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradingSessionSubId" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradSesStatus" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="fastMarketIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="quoteRequest_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="side" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="snapshotOrder_t">
    <xs:sequence>
      <xs:element name="orderDetailsComp" type="tns:orderDetailsComp_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="topOfBook_t">
    <xs:sequence>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="bidPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="offerPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="bidSize" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="offerSize" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradeReport_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdMatchId" type="xs:unsignedInt" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0xFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="matchType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="matchSubType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="algorithmicTradeIndicator" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradeReversal_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:long" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="transactTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastQty" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdRegTsExecutionTime" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0xFFFFFFFFFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trdMatchId" type="xs:unsignedInt" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" nilKind="literalValue" nilValue="0xFFFFFFFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeCondition" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad2" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="noMdEntries" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdTradeEntryGrpComp" type="tns:mdTradeEntryGrpComp_t" maxOccurs="unbounded">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element occursCountKind="expression" occursCount="{ ../noMdEntries }" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mdTradeEntryGrpComp_t">
    <xs:sequence>
      <xs:element name="mdEntryPx" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdEntrySize" type="xs:unsignedLong" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" nilKind="literalValue" nilValue="0x8000000000000000" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdEntryType" type="xs:unsignedByte" nillable="true">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" nilKind="literalValue" nilValue="0xFF" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pad7" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>