<?xml version="1.0" encoding="UTF-8"?>
<!--
  Dfdl schema definition for: Aquis AquisEquities RealTime v4.1

  Protocol:
    Organization: Aquis Exchange
    Protocol: Real Time Market Data Feed
    Encoding: Aquis Market Data Protocol
    Version: 4.1
    Date: 1/1/2026
    Specification: Unknown

  Script:
    Generator: 1.0.0.0
    License: Public/GPLv3
    Authors: Omi Developers

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under
  the license noted above.

  The protocol compiler technologies used to produce this file
  are the subject of patents owned by Scaled Sources LLC.  Those patent
  rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en

  For full Omi information:
    https://github.com/Open-Markets-Initiative/Directory

  Open Markets Initiative website:
    https://openmarketsinitiative.com
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:tns="urn:omi:aquisequities:realtime:v4:1" targetNamespace="urn:omi:aquisequities:realtime:v4:1">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="bigEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="packet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="packetHeader" type="tns:packetHeader_t" />
        <xs:element name="message" type="tns:message_t" maxOccurs="unbounded">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element occursCountKind="expression" occursCount="{ ../packetHeader/messageCount }" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="packetHeader_t">
    <xs:sequence>
      <xs:element name="messageCount" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="message_t">
    <xs:sequence>
      <xs:element name="messageHeader" type="tns:messageHeader_t" />
      <xs:element name="payload">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../messageHeader/msgLength - 6 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../messageHeader/msgType) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="orderAdd" type="tns:orderAdd_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="2" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderCancel" type="tns:orderCancel_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="3" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderModify" type="tns:orderModify_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="4" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="trade" type="tns:trade_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="5" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tradeBustMessage" type="tns:tradeBustMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="6" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="tickTableDataMessage" type="tns:tickTableDataMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="7" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="securityDefinitionMessage" type="tns:securityDefinitionMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="8" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="securityStatusMessage" type="tns:securityStatusMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="9" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="aoDUpdateMessage" type="tns:aoDUpdateMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="17" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="maCUpdateMessage" type="tns:maCUpdateMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="16" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="messageHeader_t">
    <xs:sequence>
      <xs:element name="msgType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Order Add</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Order Cancel</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Order Modify</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="6">
              <xs:annotation>
                <xs:documentation>Trade Bust Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>Tick Table Data Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="8">
              <xs:annotation>
                <xs:documentation>Security Definition Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="9">
              <xs:annotation>
                <xs:documentation>Security Status Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="17">
              <xs:annotation>
                <xs:documentation>Ao D Update Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="16">
              <xs:annotation>
                <xs:documentation>Ma C Update Message</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="msgLength" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="seqNo" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderAdd_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="side">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Buy Order</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Sell Order</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="quantity" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderRef" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdFlags" type="tns:mdFlags_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mdFlags_t">
    <xs:sequence>
      <xs:element name="unrestrictedLiquidityIndicator" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved7" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="7" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderCancel_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderRef" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdFlags" type="tns:mdFlags_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderModify_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="quantity" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderRef" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mdFlags" type="tns:mdFlags_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="trade_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeType">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Visible Order</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Hidden Order</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Market At Close</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Lis Cross</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Benchmark Cross</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="6">
              <xs:annotation>
                <xs:documentation>Auction On Demand</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="12">
              <xs:annotation>
                <xs:documentation>Aquis Vwap Match</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="quantity" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderRef" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeRef" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mic" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="binaryMmt" type="tns:binaryMmt_t" />
      <xs:element name="mdFlags" type="tns:mdFlags_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="binaryMmt_t">
    <xs:sequence>
      <xs:element name="marketMechanism">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="3" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Central Limit Order Book</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Quote Driven Market</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Dark Order Book</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Off Book</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Periodic Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="6">
              <xs:annotation>
                <xs:documentation>Rfq</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>Other</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="tradingMode">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="4" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Undefined Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Opening Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Closing Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Intraday Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Unscheduled Auction</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="6">
              <xs:annotation>
                <xs:documentation>Continuous Trading</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>At Market Close</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="8">
              <xs:annotation>
                <xs:documentation>Out Of Main Session</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="9">
              <xs:annotation>
                <xs:documentation>On Exchange Trade Reporting</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="A">
              <xs:annotation>
                <xs:documentation>Off Exchange Trade Reporting</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="B">
              <xs:annotation>
                <xs:documentation>Systematic Internalizer Trade Reporting</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="transactionCategory">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="3" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Dark Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Trade That Has Received Price Improvement</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Package Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Exchange For Physicals</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>None Apply</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="negotiationIndicatorOrPreTradeTransparencyWaiver">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="3" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>Negotiated Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Negotiated Trade In Liquid Instruments</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Negotiated Trade In Illiquid Instruments</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Negotiated Trade Other Than Current Market Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>No Negotiated Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Si Illiquid Instruments</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="6">
              <xs:annotation>
                <xs:documentation>Si Above Standard Market Size</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>Ilqd And Size</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="crossingTrade">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>No</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Yes</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="modificationIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="2" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Trade Cancelation</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Trade Amendment</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>New Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="benchmarkReferencePriceIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="2" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Benchmark Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Reference Price Trade</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>No Benchmark Or Reference Price</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="dividend">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>No</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Yes</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="offBookAutomation">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="2" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Unspecified</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Off Book Non Automated</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Off Book Automated</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="priceFormationDiscoveryProcess">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="3" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Plain Vanilla</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Non Price Forming</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Trade Not Contributing To Price Discovery</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Price Not Currently Available But Pending</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="algorithmicIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>No</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Yes</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="publicationModePostTradeDeferral">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="3" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Immediate Publication</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Non Immediate Publication</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Lrgs</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="4">
              <xs:annotation>
                <xs:documentation>Ilqd</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="5">
              <xs:annotation>
                <xs:documentation>Size</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="6">
              <xs:annotation>
                <xs:documentation>Ilqd And Size</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="7">
              <xs:annotation>
                <xs:documentation>Ilqd And Lrgs</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="deferralType" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="duplicativeIndicator">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>Unique</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Duplicative</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="spare" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tradeBustMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="quantity" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradeRef" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="binaryMmt" type="tns:binaryMmt_t" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tickTableDataMessage_t">
    <xs:sequence>
      <xs:element name="tickTableId" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="name" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="10" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="threshold" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tickSize" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="securityDefinitionMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="umtf" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="isin" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="12" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="currency" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="3" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mic" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tickTableId" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="securityDefinitionFlags" type="tns:securityDefinitionFlags_t" />
      <xs:element name="reservedChar2020" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="20" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lotSize" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lotSizeDecimal" type="xs:unsignedByte">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="securityDefinitionFlags_t">
    <xs:sequence>
      <xs:element name="macEnabled" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="testStock" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="illiquid" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved1" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="aodEnabled" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved2" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="avxEnabled" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved8" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="securityStatusMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradingStatus">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Active</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="2">
              <xs:annotation>
                <xs:documentation>Halted</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="3">
              <xs:annotation>
                <xs:documentation>Suspended</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="8">
              <xs:annotation>
                <xs:documentation>Ao D Start</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="24">
              <xs:annotation>
                <xs:documentation>Ao D End</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="marketFlags" type="tns:marketFlags_t" />
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradingPhase">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:unsignedByte">
            <xs:enumeration value="0">
              <xs:annotation>
                <xs:documentation>Closed</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="1">
              <xs:annotation>
                <xs:documentation>Continuous</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="marketFlags_t">
    <xs:sequence>
      <xs:element name="trading" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="macOpen" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="macRun" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved5" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" alignment="1" alignmentUnits="bits" lengthKind="explicit" lengthUnits="bits" length="5" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="aoDUpdateMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="indicativePrice" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="matchVol" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="maCUpdateMessage_t">
    <xs:sequence>
      <xs:element name="securityId" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="indicativePrice" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="closingBuyQty" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="closingSellQty" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="littleEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>