<?xml version="1.0" encoding="UTF-8"?>
<!-- Omi Dfdl Schema Definition: Nasdaq NsmEquities TotalView v5.0.2026 -->
<!-- Please see end of file for rules and regulations -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/" xmlns:tns="urn:omi:nsmequities:totalview:v5:0:2026" targetNamespace="urn:omi:nsmequities:totalview:v5:0:2026">
  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">
      <dfdl:format byteOrder="bigEndian" bitOrder="mostSignificantBitFirst" representation="binary" binaryNumberRep="binary" lengthKind="implicit" lengthUnits="bytes" encoding="ASCII" encodingErrorPolicy="replace" initiator="" terminator="" separator="" separatorPosition="infix" separatorSuppressionPolicy="anyEmpty" sequenceKind="ordered" initiatedContent="no" leadingSkip="0" trailingSkip="0" alignment="1" alignmentUnits="bytes" fillByte="%#r00;" ignoreCase="no" occursCountKind="implicit" truncateSpecifiedLengthString="no" textBidi="no" floating="no" textPadKind="none" textTrimKind="none" escapeSchemeRef="" />
    </xs:appinfo>
  </xs:annotation>
  <xs:element name="packet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="packetHeader" type="tns:packetHeader_t" />
        <xs:element name="messages" type="tns:message_t" maxOccurs="unbounded">
          <xs:annotation>
            <xs:appinfo source="http://www.ogf.org/dfdl/">
              <dfdl:element occursCountKind="expression" occursCount="{ ../packetHeader/messageCount }" />
            </xs:appinfo>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="packetHeader_t">
    <xs:sequence>
      <xs:element name="session" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="10" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="sequenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="messageCount" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="message_t">
    <xs:sequence>
      <xs:element name="messageHeader" type="tns:messageHeader_t" />
      <xs:element name="payload">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element lengthKind="explicit" length="{ ../messageHeader/messageLength - 1 }" />
          </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
          <xs:choice>
            <xs:annotation>
              <xs:appinfo source="http://www.ogf.org/dfdl/">
                <dfdl:choice choiceLengthKind="implicit" choiceDispatchKey="{ xs:string(../messageHeader/messageType) }" />
              </xs:appinfo>
            </xs:annotation>
            <xs:element name="systemEventMessage" type="tns:systemEventMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="S" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="stockDirectoryMessage" type="tns:stockDirectoryMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="R" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="stockTradingActionMessage" type="tns:stockTradingActionMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="H" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="regShoShortSalePriceTestRestrictedIndicatorMessage" type="tns:regShoShortSalePriceTestRestrictedIndicatorMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="Y" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="marketParticipantPositionMessage" type="tns:marketParticipantPositionMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="L" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="mwcbDeclineLevelMessage" type="tns:mwcbDeclineLevelMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="V" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="mwcbStatusLevelMessage" type="tns:mwcbStatusLevelMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="W" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="ipoQuotingPeriodUpdate" type="tns:ipoQuotingPeriodUpdate_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="K" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="luldAuctionCollarMessage" type="tns:luldAuctionCollarMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="J" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="operationalHaltMessage" type="tns:operationalHaltMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="h" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="addOrderNoMpidAttributionMessage" type="tns:addOrderNoMpidAttributionMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="A" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="addOrderWithMpidAttributionMessage" type="tns:addOrderWithMpidAttributionMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="F" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderExecutedMessage" type="tns:orderExecutedMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="E" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderExecutedWithPriceMessage" type="tns:orderExecutedWithPriceMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="C" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderCancelMessage" type="tns:orderCancelMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="X" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderDeleteMessage" type="tns:orderDeleteMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="D" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="orderReplaceMessage" type="tns:orderReplaceMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="U" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="nonCrossTradeMessage" type="tns:nonCrossTradeMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="P" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="crossTradeMessage" type="tns:crossTradeMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="Q" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="brokenTradeMessage" type="tns:brokenTradeMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="B" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="netOrderImbalanceIndicatorMessage" type="tns:netOrderImbalanceIndicatorMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="I" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="retailPriceImprovementIndicatorMessage" type="tns:retailPriceImprovementIndicatorMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="N" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
            <xs:element name="directListingWithCapitalRaisePriceDiscoveryMessage" type="tns:directListingWithCapitalRaisePriceDiscoveryMessage_t">
              <xs:annotation>
                <xs:appinfo source="http://www.ogf.org/dfdl/">
                  <dfdl:element choiceBranchKey="O" />
                </xs:appinfo>
              </xs:annotation>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="messageHeader_t">
    <xs:sequence>
      <xs:element name="messageLength" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="messageType" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="systemEventMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="eventCode" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="stockDirectoryMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketCategory" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="financialStatusIndicator" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="roundLotSize" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="roundLotsOnly" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="issueClassification" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="issueSubType" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="authenticity" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="shortSaleThresholdIndicator" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ipoFlag" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="luldReferencePriceTier" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="etpFlag" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="etpLeverageFactor" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="inverseIndicator" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="stockTradingActionMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="tradingState" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reserved" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="reasonCode" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="regShoShortSalePriceTestRestrictedIndicatorMessage_t">
    <xs:sequence>
      <xs:element name="locateCode" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="regShoAction" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="marketParticipantPositionMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="mpid" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="primaryMarketMaker" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketMakerMode" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketParticipantState" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mwcbDeclineLevelMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="level1" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="level2" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="level3" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mwcbStatusLevelMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="breachedLevel" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ipoQuotingPeriodUpdate_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ipoQuotationReleaseTime" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ipoQuotationReleaseQualifier" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="ipoPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="luldAuctionCollarMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="auctionCollarReferencePrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="upperAuctionCollarPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lowerAuctionCollarPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="auctionCollarExtension" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="operationalHaltMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="marketCode" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="operationalHaltAction" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="addOrderNoMpidAttributionMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderReferenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="buySellIndicator" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="shares" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="addOrderWithMpidAttributionMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderReferenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="buySellIndicator" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="shares" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="attribution" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderExecutedMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderReferenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="executedShares" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="matchNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderExecutedWithPriceMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderReferenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="executedShares" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="matchNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="printable" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="executionPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderCancelMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderReferenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="canceledShares" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderDeleteMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderReferenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="orderReplaceMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="originalOrderReferenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="newOrderReferenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="shares" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="nonCrossTradeMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="orderReferenceNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="buySellIndicator" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="shares" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="price" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="matchNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="crossTradeMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="crossShares" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="crossPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="matchNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="crossType" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="brokenTradeMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="matchNumber" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="netOrderImbalanceIndicatorMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="pairedShares" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="imbalanceShares" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="imbalanceDirection" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="farPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="nearPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="currentReferencePrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="crossType" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="priceVariationIndicator" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="retailPriceImprovementIndicatorMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="interestFlag" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="directListingWithCapitalRaisePriceDiscoveryMessage_t">
    <xs:sequence>
      <xs:element name="stockLocate" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="trackingNumber" type="xs:unsignedShort">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="2" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="timestamp" type="xs:hexBinary">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" lengthKind="explicit" length="6" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="stock" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="openEligibilityStatus" type="xs:string">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="text" encoding="ASCII" lengthKind="explicit" length="1" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="minimumAllowablePrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="maximumAllowablePrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="nearExecutionPrice" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="nearExecutionTime" type="xs:unsignedLong">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="8" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="lowerPriceRangeCollar" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element name="upperPriceRangeCollar" type="xs:unsignedInt">
        <xs:annotation>
          <xs:appinfo source="http://www.ogf.org/dfdl/">
            <dfdl:element representation="binary" binaryNumberRep="binary" byteOrder="bigEndian" lengthKind="explicit" length="4" />
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
<!--
  Omi Dfdl schemas are declarative cross platform binary format descriptions.  Feel free to modify.  Enjoy.

  Protocol: Nasdaq NsmEquities TotalView v5.0.2026

  Copyright (c) 2026 Scaled Sources LLC.  https://www.scaledsources.com

  This dfdl schema is contributed to The Open Markets Initiative under the license noted above.

  The Binary Data Compiler technologies used to produce this file are the subject of patents owned
  by Scaled Sources LLC.  Those patent rights are retained and are not transferred by this contribution:
    https://patents.google.com/patent/US20240129382A1/en
    https://patents.google.com/patent/US20240419416A1/en
-->
